spring.application.name=Employees_management

# ==========================================
# PRODUCTION FIX: Dynamic Variable Parsing with Secure Hard Fallback
# ==========================================
# Agar Render ka DATABASE_URL load nahi hua, toh pipeline default link (colon `:` ke baad wala) utha legi
spring.datasource.url=${DATABASE_URL:jdbc:mysql://u5mmnsasgroi8lt5:PX1wdUMWd4HbS6U0SP9k@bxvgbkzszlbe2jqtofon-mysql.services.clever-cloud.com:3306/bxvgbkzszlbe2jqtofon}
spring.datasource.username=${DATABASE_USERNAME:u5mmnsasgroi8lt5}
spring.datasource.password=${DATABASE_PASSWORD:PX1wdUMWd4HbS6U0SP9k}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE ENGINE SETTINGS
# ==========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# SPRING BOOT ACTUATOR & MONITORING CONFIGS
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ==========================================
# HIKARI CONNECTION POOL OPTIMIZATION
# ==========================================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000