spring.application.name=Employees_management
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql

# JPA / Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# SPRING BOOT ACTUATOR & MONITORING CONFIGS
# ==========================================

# Saare monitoring endpoints ko web access par exposure dena
management.endpoints.web.exposure.include=*

# Health endpoint ke andar database aur disk space ki detailed report dekhna
management.endpoint.health.show-details=always
